// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2pL_AOQFfbg_9bNk_Aes6ETqoVpYLbRY',
    appId: '1:541477768814:web:16ed741d894883d503a07f',
    messagingSenderId: '541477768814',
    projectId: 'wordgamewithpals',
    authDomain: 'wordgamewithpals.firebaseapp.com',
    storageBucket: 'wordgamewithpals.appspot.com',
    measurementId: 'G-1NCKFZWYT0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP9WUGLVzehGUc1YyQKpsB8Qdo562HIyk',
    appId: '1:541477768814:android:2c5d4268a10f591103a07f',
    messagingSenderId: '541477768814',
    projectId: 'wordgamewithpals',
    storageBucket: 'wordgamewithpals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3DxngyVyxo3_jyUSOQ8JYbiLvkIwKDAY',
    appId: '1:541477768814:ios:5907f1d8a0e5e8c503a07f',
    messagingSenderId: '541477768814',
    projectId: 'wordgamewithpals',
    storageBucket: 'wordgamewithpals.appspot.com',
    iosBundleId: 'com.example.wordgamewithpals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3DxngyVyxo3_jyUSOQ8JYbiLvkIwKDAY',
    appId: '1:541477768814:ios:4272760ad5771ba003a07f',
    messagingSenderId: '541477768814',
    projectId: 'wordgamewithpals',
    storageBucket: 'wordgamewithpals.appspot.com',
    iosBundleId: 'com.example.wordgamewithpals.RunnerTests',
  );
}
